name: Generate terraform docs
on:
  push:
    branches:
      - main # Adjust the branch name as needed

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }} # This ensures the code at the pushed ref is checked out

      - name: Render terraform docs and push changes back to main
        uses: terraform-docs/gh-actions@main
        with:
          working-dir: .
          output-file: README.md
          output-method: inject
          git-push: "true"
          git-commit-message: "Auto generate Terraform docs commit"
